# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import swingtime.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refugee_manager', '0005_auto_20171103_2341'),
        ('employment_manager', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('employment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employment_manager.EmploymentClient')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=4, unique=True, verbose_name='abbreviation')),
                ('label', models.CharField(max_length=50, verbose_name='label')),
            ],
            options={
                'verbose_name': 'event type',
                'verbose_name_plural': 'event types',
            },
        ),
        migrations.CreateModel(
            name='ICal_Calendar',
            fields=[
                ('slug', models.CharField(default=swingtime.models.genslug, max_length=32, primary_key=True, serialize=False)),
                ('everything', models.BooleanField(default=False)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee_manager.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='swingtime.Event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'occurrence',
                'verbose_name_plural': 'occurrences',
                'ordering': ('start_time', 'end_time'),
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swingtime.EventType', verbose_name='event type'),
        ),
        migrations.AddField(
            model_name='event',
            name='refugee_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refugee_manager.Case'),
        ),
    ]
